---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops-demo-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gitops-demo-2
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 0582644446.dkr.ecr.ap-southeast-2.amazonaws.com/rokko2008/my-nginx:34
        ports:
        - name: web
          containerPort: 80
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
      imagePullSecrets:
        - name: mysecret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - general
